<<<<<<< HEAD
# Site settings

title: 窗外蟋蟀
SEOTitle: 窗外蟋蟀的博客 | Keysaim Blog
header-img: img/home-bg-hill.jpg
email: keysaim@gmail.com
description: "描述"
keyword: "窗外蟋蟀, keysaim"
url: "https://keysaim.github.io"
baseurl: ""
theme: minima

=======
theme:minima

theme: jekyll-theme-cayman
>>>>>>> fd042a4558a21372f72b63f2a3fe1c9cd082fba3
