# Site settings

title: XuS's Blog
SEOTitle:  XuS Blog
# header-img: img/home-bg-hill.jpg
# email: keysai@gmail.com
description: "XuS's Coding Blog"
keyword: "Coding, XuS"
url: "https://yehuo.github.io"
baseurl: "/"
theme: minima

